---

- hosts: tux-mai02.inverso.local
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "7.9"

  - name: install httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
