---

- hosts: tux-mai02.inverso.local
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes


  - name: install httpd package
    yum:
      name: httpd
      state: absent

  - name: add php support for apache
    yum:
      name: php
      state: absent
