---

#- hosts: all
#  become: true
#  pre_tasks:

#  - name: update repository index (CentOS)
#    tags: always
#    yum:
#      update_cache: yes
#    changed_when: false
#    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles: 
    - web_servers

- hosts: all
  become: true
  roles:
    - base

#- hosts: workstations
#   become: true
#   roles:
#     - workstations 
