- name: install httpd and php package
  tags: centos, httpd
  yum:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: present

- name: start and enable httpd
  tags: apache httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail address for admin mai02
  tags: apache, httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin root@localhost    # change the email line here
  when: ansible_distribution == "CentOS"
  notify: restart_apache
#  register: httpd

#- name: restart httpd (CentOS)
#  tags: apache, httpd
#  service:
#    name: "{{ apache_service }}"
#    state: restarted
#  when: httpd.changed

- name: copy default html file for site
  tags: httpd, apache
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

